GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text":"Ok, this works"
}

###

DELETE http://localhost:3001/todo/delete/65f13a9f9765a68618242af2

###

PUT http://localhost:3001/todo/complete/65f21991811a182a5ac35f30